Create dev environment
COHHIO/ryha pull request #105
Opened 2024-06-18 13:43 UTC by IvanM26

# List of changes:
- Added files to create a dev container that leverages `docker-compose` to set up a development environment with three services:
    - `app`, the application container that installs the proper R version and uses `renv` to install proper R packages versions. This service also leverages `renv` cache functionality.
    - `db`, which sets up a postgreSQL database
    - `pgadmin`, which sets up pgAdmin (database management system)
- Updated different configuration files (i.e. added new entries to `.gitignore`, updated DESCRIPTION to allow the use of markdown in roxygen comments, updated packages versions in `renv.lock`).
- Improved `create_dm()`. I added a new parameter that reads an environmental variable to determine how the data model is created. This avoids the necessity to change app code to alternate between production and non-production data.
- Added `postgres/populate_dev_database/populate_dev_database.R`, a script to populate dev database.
- Added "Development Environment" section to README.
- Included an example "Production" Dockerfile, which is not used for now (as we deploy to shinyapps.io).

# How to test
You should be able to read the "Development Environment" README section and:
1. Open the repository in a dev container (leveraging `renv` cache)
2. Populate the development database
3. Explore the development database in pgAdmin
4. Connect to the database outside of the dev container (for example, from RStudio in the local machine)

# Additional comments
- Check whether we need to improve the README
- Check whether we need to change filenames
- Check whether the new parameters are documented properly in the roxygen comments

Closes #104

2024-07-03 20:39 UTC, mthomas-ketchbrook commented on Dockerfile
Is there any practical use for this file currently?

2024-07-03 20:43 UTC, mthomas-ketchbrook commented on R/fct_create_dm.R
> +  # instead of taking "prod" as the default value if nothing is supplied
Please address this TODO

2024-07-03 20:43 UTC, mthomas-ketchbrook commented on R/fct_create_dm.R
> +  # instead of taking "prod" as the default value if nothing is supplied
Please address this TODO

2024-07-03 20:45 UTC, mthomas-ketchbrook commented on R/mod_upload.R
> +      # TODO // Add an error if you're connecting via "file"
Please address this TODO

2024-07-03 20:48 UTC, mthomas-ketchbrook commented on README.Rmd
> +  * `CREATE_DM_ENV`
Can we change this to `APP_BACKEND`?  Valid values will still be "prod", "dev", and "file".  It would be nice to specify in the README what valid values are (and why), as well as briefly explain what the other environment variables listed represent.

I realize that this will cause downstream changes elsewhere in the repository where we use the `CREATE_DM_ENV` environment variable.

2024-07-03 20:53 UTC, mthomas-ketchbrook commented on README.Rmd
> +- `.env` defines environmental variables used to configure `{renv}`'s cache. **Remember to change `RENV_PATHS_CACHE_HOST` as appropriate for your system**.
Let's update this to explain that `.env.example` is an *example* file that sets the `RENV_PATHS_CACHE_HOST` environment variable, and the user will have to copy it and create another file named `.env` in the same directory as `.env.example` and change the value to a path on their local machine based upon  https://rstudio.github.io/renv/articles/package-install.html?q=cache%20location#cache-location

2024-07-03 20:55 UTC, mthomas-ketchbrook commented on README.Rmd
> +`.devcontainer` directory contains the necessary files to set up a [development container](https://code.visualstudio.com/docs/devcontainers/containers):
In general, can we create links for actual files (e.g., `.devcontainer`) instead of treating them like code?  This will allow users to quickly jump to the file we are taking about, or open it in a new browser window/tab.

2024-07-03 20:56 UTC, mthomas-ketchbrook commented on README.Rmd
> +
Let's add a `### QuickStart` section that says "Once you have the requirements installed, have cloned the repo locally, and created the `.devcontainer/.env` file, open the repository in VSCode and click "Reopen in Container"...

2024-07-03 20:58 UTC, mthomas-ketchbrook commented on README.Rmd
As a high-level comment, do we think it makes sense to have a specific README in the `.devcontainer` directory, and move the Dev Container setup information there?  We could create a link to it in the root-level README.

2024-07-03 21:01 UTC, mthomas-ketchbrook requested changes
Some changes are requested in the inline comments.

If we choose to alter the `connect_to_db()` and `create_dm()` functions so that a "prod"/"dev"/"file" argument is *required* from the user, we should update any Roxygen examples accordingly.

2024-07-05 12:15 UTC, IvanM26 commented on Dockerfile
This file is not currently used. I considered that it was nice to have a "theoretical" file that could be used in case we moved from shinyapps.io to ShinyProxy. In addition, I thought of this file as a possible "reference" for the future. Do you think it makes sense to delete it for now?

2024-07-05 12:22 UTC, IvanM26 commented on R/fct_create_dm.R
> +  # instead of taking "prod" as the default value if nothing is supplied
The comment has been addressed. Take into account that `connect_to_db()` only accepts `"prod"` and `"dev"` as valid values. When we use `file` there is no database connection!

2024-07-05 12:42 UTC, IvanM26 commented on R/fct_create_dm.R
> +  # instead of taking "prod" as the default value if nothing is supplied
The comment has been addressed.

2024-07-05 14:16 UTC, IvanM26 commented on README.Rmd
> +  * `CREATE_DM_ENV`
Changes were applied. I improved the README section to be as clear as possible regarding the additional configuration that needs to be set up before running the app.

2024-07-05 14:26 UTC, IvanM26 commented on R/mod_upload.R
> +      # TODO // Add an error if you're connecting via "file"
The modification to `connect_to_db()` addressed this comment. As data upload requires a database connection, I think the error message does not need to specify that we were trying to upload data when we have APP_BACKEND set to `"file"`.

2024-07-05 16:06 UTC, IvanM26 commented on README.Rmd
> +`.devcontainer` directory contains the necessary files to set up a [development container](https://code.visualstudio.com/docs/devcontainers/containers):
Done!

2024-07-05 16:59 UTC, IvanM26 commented on README.Rmd
> +
Done!

2024-07-10 11:50 UTC, IvanM26 commented
Requested changes have been applied. If any other changes need to be done, let me know!

2024-07-15 18:42 UTC, mthomas-ketchbrook approved these changes
Fantastic work on this!  The only thing I'm seeing (that we should pursue in a separate issue) are some {readr} parsing warnings when uploading the test .zip file.

Upon the next merge into 'main', let's remember to update the `DESCRIPTION` to add @IvanM26 as a contributor, and increment the package version.

2024-07-15 18:42 UTC, merged