Add ungrouped destination chart
COHHIO/ryha pull request #95
Opened 2024-04-15 21:05 UTC by IvanM26

A new chart was added to Living Situation page. This chart shows the number of youth by destination. The difference with the pie chart ("at Exit") is that this new chart shows the categories without grouping. To make the distinction clear, titles were updated accordingly. As part of this task the title in Education page was updated as well to keep consistency throughout the app codebase. As a final note, some packages were updated.

2024-04-15 21:49 UTC, mthomas-ketchbrook requested changes
Hi @IvanM26 -- great work! I'm recommending a few small changes, and we should brainstorm on how to better display the new horizontal bar chart for "Living Situation" so that the bars/labels aren't so condensed.

2024-04-15 21:49 UTC, mthomas-ketchbrook commented on R/mod_living_situation.R
> +          height = "680px",
I assume this box's height is taller than the `DEFAULT_BOX_HEIGHT` to accommodate the large number of categories on the y-axis?

2024-04-15 21:49 UTC, mthomas-ketchbrook commented on R/mod_living_situation.R
> +          height = "680px",
The y-axis labels are very long, which makes the the x-axis labels too close together and takes away from the data in the chart (bars) itself.  Let's consider how we can improve this (perhaps by trimming some of the labels).
![image](https://github.com/COHHIO/ryha/assets/52801195/9e933767-af26-45d1-be51-0f42735ccebd)

2024-04-15 21:49 UTC, mthomas-ketchbrook commented on R/mod_living_situation.R
> +                              "Client prefers not to answer")
We should also remove "No exit interview completed" (see chart above) -- I believe that would belong in the "Data Quality Statistics" section. @trevinflick do you agree?

2024-04-15 21:49 UTC, mthomas-ketchbrook commented on R/mod_education.R
We should add "Group" to the box title for the sankey chart, as well.

2024-04-16 13:40 UTC, IvanM26 commented on R/mod_living_situation.R
> +          height = "680px",
Regarding the first comment, it is like you say! I needed to increase the chart height due to the number of different categories.

Regarding the second comment, I have trimmed the label text. Long labels now end with an ellipsis. Users can see the full name by hovering over the bar.

2024-04-16 13:44 UTC, IvanM26 commented on R/mod_living_situation.R
> +                              "Client prefers not to answer")
As you mention, that value should not be shown in the chart. I see that the other charts are removing that category (as well as `Worker unable to determine`). So I will add both categories to the filter.

2024-04-16 13:49 UTC, IvanM26 commented on R/mod_education.R
Done!

2024-04-16 15:22 UTC, mthomas-ketchbrook approved these changes

2024-04-16 15:23 UTC, merged