Improve documentation and tests
COHHIO/ryha pull request #98
Opened 2024-04-27 21:36 UTC by IvanM26

# Changes
- Added documentation (using roxygen comments) to some functions
- Added unit tests for some functions
- Added a new parameter to `check_file_names()` to be able to properly create the unit test
- Deleted tests for a non-existent function
- Applied some code styling

# Additional comment
- Functions that require a database connection (such as `read_data_from_table()` are not currently tested. We could create an in-memory database with `dbConnect(RSQLite::SQLite(), ":memory:")` but that would involve adding an extra dependency we don't want to add.

# Test
- Checkout to the branch and run devtools::test(). Some functions create temp folders and files to be able to perform tests. We need to make sure that this is implemented correcly
- Check that the new parameter of `check_file_names()` isn't breaking functionality. I would assume that it shouldn't

2024-05-01 02:48 UTC, mthomas-ketchbrook requested changes
This looks great!  Just a few small questions and change requests.

2024-05-01 02:48 UTC, mthomas-ketchbrook commented on R/fct_generate_charts.R
> -}
Is this function not being called in the app anywhere?

2024-05-01 02:48 UTC, mthomas-ketchbrook commented on R/fct_generate_charts.R
> +  # TODO: Check scenario where a person has start-end-start.
Let's not lose sight of this... we should open another issue to address it.

2024-05-01 02:48 UTC, mthomas-ketchbrook commented on R/utils_process_data.R
> +
This is probably a good idea just so that in future iterations we don't alter these tables by accident.

2024-05-01 02:48 UTC, mthomas-ketchbrook commented on tests/testthat/test-utils_ingest_checks.R
Can we write the `expect_equal()` calls as multi-line with the following styling?

```
expect_equal(
   expression_1,
   expression_2
)
```

It's a little difficult for me to see the two expressions separately, since some of the `expression_1` values are nested functions themselves.

2024-05-01 02:48 UTC, mthomas-ketchbrook commented on tests/testthat/test-utils_process_data.R
> +    "some/path/to/file/data2.csv"
This feels a little too "hard-coded", and while this test is small, I think this is an important test to have in place as the package matures.  Can we leverage `tempfile`/`tempdir` to programmatically create a directory and find the file?

2024-05-01 02:48 UTC, mthomas-ketchbrook commented on tests/testthat/test-utils_process_data.R
> +  expect_equal(find_file(mock_filepaths, "data1"), "some/path/to/file/data1.csv")
Can we write the `expect_equal()` call as multi-line with the following styling?

```
expect_equal(
   expression_1,
   expression_2
)
```

It's a little difficult for me to see the two expressions separately, since some of the `expression_1` values are nested functions themselves.

2024-05-01 02:48 UTC, mthomas-ketchbrook commented on R/fct_generate_charts.R
Why are the examples wrapped in `\dontrun{}` ?

2024-05-01 03:16 UTC, mthomas-ketchbrook commented
Verified tests pass successfully on R 4.3.3 using `eddelbuettel/r2u:22.04` Docker image ✅

2024-05-07 13:01 UTC, IvanM26 commented on R/fct_generate_charts.R
> -}
As far as I checked (using "Find in Files") the function is not called in the app. Also, I ran the app without the function defined and the heatmap is shown properly.

2024-05-07 13:39 UTC, IvanM26 commented on R/fct_generate_charts.R
> +  # TODO: Check scenario where a person has start-end-start.
New issue created https://github.com/COHHIO/ryha/issues/100.

2024-05-07 13:53 UTC, IvanM26 commented on R/utils_process_data.R
> +
I added an additional condition to the `if` statement. Please check that it will work as expected, as I can't test it due to lack of access to database. I think the syntax is okay, we need to check if the organization table is named like so!

2024-05-07 13:57 UTC, IvanM26 commented on tests/testthat/test-utils_ingest_checks.R
Done!

2024-05-07 14:11 UTC, IvanM26 commented on tests/testthat/test-utils_process_data.R
> +  expect_equal(find_file(mock_filepaths, "data1"), "some/path/to/file/data1.csv")
Done!

2024-05-07 14:25 UTC, IvanM26 commented on tests/testthat/test-utils_process_data.R
> +    "some/path/to/file/data2.csv"
Done!

2024-05-07 15:15 UTC, IvanM26 commented on R/fct_generate_charts.R
It was a misunderstanding on my side. They have been addressed accordingly!

2024-05-07 15:16 UTC, IvanM26 commented
Suggested changes have been applied.

2024-06-10 03:28 UTC, mthomas-ketchbrook approved these changes

2024-06-10 03:28 UTC, merged